add set -e to test.yaml

diff --git a/.github/workflows/test.yaml b/.github/workflows/test.yaml
--- a/.github/workflows/test.yaml
+++ b/.github/workflows/test.yaml
@@ -58,7 +58,13 @@ jobs:
         run: | 
           ici \
             --rcwd "${{ env.remote_build_dir }}" \
-            --cmd "/QOpenSys/pkgs/bin/gmake --jobs=1 testonly; exit $?" \
+            --cmd " |
+                set -e  # Exit on any error
+                /QOpenSys/pkgs/bin/gmake testonly || { 
+                  echo "Tests failed, killing background process"
+                  ps -ef | grep manzan | awk '{ print $2 }' | xargs kill -9
+                  exit 1; 
+                }" \
         env:
           IBMI_HOST: ${{ secrets.IBMI_HOST }}
           IBMI_USER: ${{ secrets.IBMI_USER }}
